ArtShop/Models/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArtShop.Models
{
    public class CartViewModel
    {
        public int Id { get; set; }
        public Guid Guid { get; set; }
        public int Amount { get; set; }
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }

    }
}

ArtShop/Models/ErrorViewModel.cs
using System;

namespace ArtShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArtShop/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ArtShop.Models;

namespace ArtShop.Models
{
    public class ProductViewModel
    {
        //get och set properties
        //från databasens kolumner
        public int Id { get; set; }
        public string Title {get; set;}
        public string Description {get; set;}
        public string Technique {get; set;}
        public string Image {get; set;}
        public int Price { get; set; }
    }
}

ArtShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using Dapper;
using ArtShop.Models;
using ArtShop.Project.Core.Models;
using Artshop.Project.Core.Repositories.Implementations;
using Artshop.Project.Core.Services;


namespace ArtShop.Controllers
{
    public class CartController : Controller
    {
        private static List<CartViewModel> Cart = new List<CartViewModel>();
        private readonly string connectionString;
        private CartService cartService;

        public CartController(IConfiguration configuration)
        {
            this.connectionString = configuration.GetConnectionString("ConnectionString");

            this.cartService = new CartService(
            new CartRepository(
            configuration.GetConnectionString("ConnectionString")));
        }


        public IActionResult Index()
        {
            var cartId = Request.Cookies["customerCookie"];
            var cart = this.cartService.GetAll(cartId);
            return View(cart);
        }

        [HttpPost]
        public IActionResult Add(ProductViewModel model)
        {
            var cookie = Request.Cookies["customerCookie"];
            this.cartService.PostToCart(model.Id, cookie);
            return RedirectToAction("Index");
        }
    }
}

ArtShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ArtShop.Models;

namespace ArtShop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArtShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using Dapper;
using ArtShop.Models;
using Artshop.Project.Core.Repositories.Implementations;
using Artshop.Project.Core.Services;
using ArtShop.Project.Core.Models;
using Microsoft.AspNetCore.Http;

namespace ArtShop.Controllers
{
    public class OrderController : Controller
    {
        private static List<OrderViewModel> checkout = new List<OrderViewModel>();
        private readonly string connectionString;
        private OrderService orderService;

        public OrderController(IConfiguration configuration)
        {
            this.connectionString = configuration.GetConnectionString("ConnectionString");
            this.orderService = new OrderService(new OrderRepository(this.connectionString), new CartRepository(this.connectionString));
        }

        public IActionResult Index()
        {
            var cartId = Request.Cookies["customerCookie"];
            var Cart = this.orderService.GetAll(cartId);
            return View(Cart);
        }

        [HttpPost]
        public IActionResult Index(OrderViewModel model, string cookie, string customerCookie)
        {
            this.orderService.PostToOrder(model.Firstname, model.Lastname, model.Email, model.Address, model.Zipcode, Request.Cookies["customerCookie"]);

            cookie = Request.Cookies["customerCookie"];
            this.orderService.DeleteCart(cookie);

            return RedirectToAction("Index");
        }
    }
}

ArtShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using Dapper;
using ArtShop.Project.Core.Models;
using Artshop.Project.Core.Repositories.Implementations;
using Artshop.Project.Core.Services;

namespace ArtShop.Controllers
{
    public class ProductsController : Controller
    {
        private static List<ProductViewModel> art = new List<ProductViewModel>();

        private readonly ProductService productService;

        public ProductsController(IConfiguration configuration)
        {
            this.productService = new ProductService(
                new ProductRepository(
                configuration.GetConnectionString("ConnectionString")));
        }

        public IActionResult Index()
        {
            List<ProductViewModel> art;
            art = this.productService.GetAll();

            if (Request.Cookies["customerCookie"] == null)
            {
                var GuId = Guid.NewGuid();
                Response.Cookies.Append("customerCookie", GuId.ToString());
            }

            return View(art);
        }

    }
}

ArtShop/Views/Cart/Cart.cshtml
@model CartViewModel

<tr>
    <th scope="col">
        <img class="cartImage" src="~/images/@Model.Image" alt="product image" />
    </th>
    <th scope="col">
        <p class="padding"> Item name: @Model.Title</p>
    </th>
    <th scope="col">
        <p class="padding"> Price: @Model.Price</p>
    </th>
</tr>

ArtShop/Views/Cart/Index.cshtml
@model List<ArtShop.Project.Core.Models.CartViewModel>
@{
    ViewData["Title"] = "Index";
}

<h2>My shopping cart</h2>
<div class="table-responsive">

    <table class="table table-striped">

        @foreach (var product in Model)
        {
            Html.RenderPartial("Cart", product);
        }

    </table>
</div>

ArtShop/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ArtShop/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ArtShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ArtShop/Views/Order/Index.cshtml
@model ArtShop.Project.Core.Models.OrderViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Order</h2>

<ul class="list-group">
    @foreach (var Product in Model.Cart)
    {
        <li class="list-group-item">
            @(Product.Title)
            @(Product.Price)
        </li>
    }
</ul>

<p class="h6 mb-4">Please enter your information below to place your order</p>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Firstname)
        @Html.TextBoxFor(model => model.Firstname, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <i class="fa fa-envelope prefix"></i>
        @Html.LabelFor(model => model.Lastname)

        @Html.TextBoxFor(model => model.Lastname, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <i class="fa fa-envelope prefix"></i>
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <i class="fa fa-user prefix"></i>
        @Html.LabelFor(model => model.Address)
        @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
    </div>

    <div class="md-form">
        <i class="fa fa-map prefix"></i>
        @Html.LabelFor(model => model.Zipcode)
        @Html.TextBoxFor(model => model.Zipcode, new { @class = "form-control" })
    </div>

    <button class="btn btn-primary" type="submit">Send order</button>
}

ArtShop/Views/Products/Index.cshtml
@model List<ArtShop.Project.Core.Models.ProductViewModel>
@{
    ViewData["Title"] = "Index";
}

<h2>Art</h2>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            @foreach (var painting in Model)
            {
                Html.RenderPartial("art", painting);
            }
        </div>
    </div>
</div>

ArtShop/Views/Products/art.cshtml
@model ArtShop.Project.Core.Models.ProductViewModel

<div class="card products">
    <div class="card-body">
        <img class="card-img-top" src="~/images/@Model.Image" alt="product image" />
        <h3 class="card-title">@Model.Title</h3>
        <p class="card-text"> @Model.Description</p>
        <p class="card-text"> @Model.Technique</p>
        <p class="card-subtitle"> @Model.Price</p>

        @using (Html.BeginForm("Add", "Cart"))
        {
            @Html.HiddenFor(m => m.Id)
            <button class="btn btn-primary" type="submit">Buy</button>
        }
    </div>
    <br />
</div>

ArtShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArtShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">ArtShop</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Products</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="Index">Cart</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Index">Order</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ArtShop by Emma Alborn</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>